name: "Hello World Action"
description: "My first Github Action"
author: "cgmoreno@uninorte.edu.co"

inputs:
  MY_NUM:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
