name: "Hello World Action"
description: "My first Github Action"
author: "cgmoreno@uninorte.edu.co"

inputs:
  MY_NUM:
    description: "Programa pa encontrar los numeros de la serie de Fibonacci"
    required: true


runs:
  using: "docker"
  image: "Dockerfile"
